server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blogdb
    username: blog
    password: blog
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
